### ISSUE TITLE
MLCD with Vit-B32 + COYO 700M model inquiry

### ISSUE THREAD

**Issue by briliantnugraha** [deepglint/unicom#29]
https://huggingface.co/spaces/DeepGlint-AI/README/discussions/1
Dear authors, thanks for the paper and code sharing, it's been quite an eye opener.
Btw, Could I know, do you plan to open source the model mentioned in the title?

Thanks in advance, Brilian

**Comment by anxiangsir** [comment]
Thank you for your attention. We have released this model, available at the following link:

https://huggingface.co/DeepGlint-AI/mlcd-vit-base-patch32-224

**Comment by briliantnugraha** [comment]
Got it, thanks again for the fast response and the awesome research + code
