### ISSUE TITLE
运行infer.py 输入图片后出错

### ISSUE THREAD

**Issue by hh-kai** [deepglint/unicom#70]
<img width="1622" alt="无标题" src="https://github.com/user-attachments/assets/01f621a6-3bd3-4f0a-921b-02fca426d726">

cu12.1+torch2.1
跑7B需要多少显存？
1.5B的模型什么时候发布啊

**Comment by anxiangsir** [comment]
我们没有在windows上测试过，建议使用linux系统搭建环境；
7B需要30G显存；
1.5B一周后发布。

**Comment by hh-kai** [comment]
好的 谢谢
