### ISSUE TITLE
ERROR   torchrun retrieval.py --batch_size 1 --dataset cub --epochs 1 --gradient_acc 1  --model_name ViT-B/32

### ISSUE THREAD

**Issue by fengminxuan** [deepglint/unicom#9]
..

**Comment by anxiangsir** [comment]
你好，你可以贴一下报错的 日志：

这里我猜测的主要原因是，这个ViT结构的最后是有BN的，BN是不支持batchsize为1时候的训练，至少batchsize为2，另外建议有BN的时候，batchsize设置>16


Hello, could you please share the error log?

The main reason for the error is that the ViT structure has a BN layer at the end, which does not support training with batch size 1. The minimum recommended batch size is 2. Also, it's advisable to set the batch size to >16 when using BN layers.

**Comment by fengminxuan** [comment]
我像这样把CUB_200_2011贴到了data下，因为--eval我得到了83.几的结果，所以dataset应该问题不大。







然后把unicom文件夹 挂载到Ubuntu环境下运行&nbsp;&nbsp;torchrun retrieval.py --batch_size 2 --dataset cub --epochs 1&nbsp; --model_name ViT-B/32
这次batch_size我调成了2，得到了以下错误







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepglint/unicom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月8日(星期四) 晚上8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deepglint/unicom] ERROR   torchrun retrieval.py --batch_size 1 --dataset cub --epochs 1 --gradient_acc 1  --model_name ViT-B/32 (Issue #9)





 
你好，你可以贴一下报错的 日志：
 
这里我猜测的主要原因是，这个ViT结构的最后是有BN的，BN是不支持batchsize为1时候的训练，至少batchsize为2，另外建议有BN的时候，batchsize设置&gt;16
 
Hello, could you please share the error log?
 
The main reason for the error is that the ViT structure has a BN layer at the end, which does not support training with batch size 1. The minimum recommended batch size is 2. Also, it's advisable to set the batch size to &gt;16 when using BN layers.

**Comment by fengminxuan** [comment]
邮箱回复，图片没了
![0a904a39da59446a15a24f7deabd5614](https://github.com/deepglint/unicom/assets/26196985/3b66cca3-08c1-406c-a39b-91119f986a4e)
![dc5c5551992dcc97faf8a5f6eb273939](https://github.com/deepglint/unicom/assets/26196985/8e0848e0-c540-43ee-b3ea-4b6f1216b9f5)

**Comment by anxiangsir** [comment]
建议使用linux服务器进行训练
